package Net::KashFlow;
#use Carp qw/croak/;
use warnings;
use strict;
use Net::KashFlowAPI; # Autogenerated SOAP::Lite stubs

=head1 NAME

Net::KashFlow - Interact with KashFlow accounting web service

=head1 SYNOPSIS

    my $kf = Net::KashFlow->new(username => $u, password => $p);

=head1 METHODS

=head2 new

Simple constructor - requires "username" and "password" named
parameters.

=cut

our $VERSION = '0.01';

sub new {
    my ($self, %args) = @_;
    for (qw/username password/) { 
        croak("You need to pass a '$_'") unless $args{$_};
    }
    bless { %args }, $self;
}

sub c {
    my ($self, $method, @args) = @_;
    my ($result, $status, $explanation) = 
        KashFlowAPI->$method($self->{username}, $self->{password}, @args);
    if ($explanation) { die($explanation) }
    return $result;
}

=head2 get_customer($id | $email)

Returns a Net::KashFlow::Customer object for the given customer. If the
parameter passed has an C<@> sign then this is treated as an email
address and the customer looked up email address; otherwise the
customer is looked up by customer code. If no customer is found in the
database, nothing is returned.

=cut

sub get_customer {
    my ($self, $thing, $by_id) = @_;
    my $method = "GetCustomer"; if ($thing =~ /@/) { $method.="ByEmail" }
    if ($by_id) { $method.="ByID" }
    my $customer;
    eval { $customer = $self->c($method, $thing) };
    if ($@ =~ /no customer/) { return } die $@."\n" if $@;
    $customer = bless $customer, "Net::KashFlow::Customer";
    $customer->{kf} = $self;
    return $customer;
}

=head2 get_customer_by_id($internal_id)

Like C<get_customer>, but works on the internal ID of the customer.

=cut

sub get_customer_by_id { $_[0]->get_customer($_[1], 1) }

=head2 get_customers

Returns all customers

=cut

sub get_customers { 
    my $self = shift;
    return map { $_->{kf} = $self; bless $_, "Net::KashFlow::Customer" }
        @{$self->c("GetCustomers")->{Customer}};
}

=head2 create_customer({ Name => "...", Address => "...", ... });

Inserts a new customer into the database, returning a
Net::KashFlow::Customer object.

=cut

sub create_customer {
    my ($self, $data) = @_;
    use Data::Dumper;
    my $id = $self->c("InsertCustomer", $data);
    return $self->get_customer_by_id($id);
}

package Net::KashFlow::Customer;
use base 'Class::Accessor';
__PACKAGE__->mk_accessors(qw( 
 Contact Address2 ShowDiscount CheckBox1 EC OutsideEC PaymentTerms Discount
 Postcode CheckBox2 Website ExtraText1 Source Email Notes ExtraText2 Mobile
 Updated Telephone Code CustomerID Address1 Address4 Created Name Address3 Fax
));

=head1 Net::KashFlow::Customer

    my $c = $kf->get_customer($email);

    $c->Telephone("+44.500123456");
    $c->update;

    print $c->Address1(), $c->Address2();

Customer objects have accessors as specified by
C<http://accountingapi.com/manual_class_customer.asp> - these accessors
are not "live" in that changes to them are only sent to KashFlow on call
to the C<update> method.

This package also has a C<delete> method to remove the customer from the
database, and an C<invoices> method which returns all the
C<Net::KashFlow::Invoice> objects assigned to this customer.

=cut

sub update {
    my $self = shift;
    my $copy = { %$self }; delete $copy->{kf};
    $self->{kf}->c("UpdateCustomer", $copy);
}

sub delete {
    my $self = shift;
    my $copy = { %$self }; delete $copy->{kf};
    $self->{kf}->c("DeleteCustomer", $copy);
}

sub invoices {
    my $self = shift;
    return map { $_->{kf} = $self->{kf}; bless $_, "Net::KashFlow::Invoice" }
        @{$self->{kf}->c("GetInvoicesForCustomer", $self->CustomerID)->{Invoice}};
}

=head1 AUTHOR

Simon Cozens, C<< <simon at simon-cozens.org> >>

=head1 BUGS

Please report any bugs or feature requests to C<bug-net-kashflow at rt.cpan.org>, or through
the web interface at L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Net-KashFlow>.  I will be notified, and then you'll
automatically be notified of progress on your bug as I make changes.




=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc Net::KashFlow


You can also look for information at:

=over 4

=item * RT: CPAN's request tracker

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-KashFlow>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/Net-KashFlow>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/Net-KashFlow>

=item * Search CPAN

L<http://search.cpan.org/dist/Net-KashFlow/>

=back


=head1 ACKNOWLEDGEMENTS


=head1 COPYRIGHT & LICENSE

Copyright 2009 Simon Cozens.

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.


=cut

1; # End of Net::KashFlow
